export const subtitle = [
	"晚风会收纳所有没说出口的情绪",
	"The evening wind holds all unspoken feelings",
	"和自己和解，是终身必修课",
	"Making peace with yourself is lifelong",
	"允许一切发生，也允许自己落空",
	"Let everything happen, let hopes fade too",
	"平凡日常里藏着细碎温柔",
	"Tiny tenderness hides in ordinary days",
	"不必追赶别人的节奏",
	"No need to follow others' pace",
	"独处不是孤独，是自我沉淀",
	"Solitude is not loneliness, but reflection",
	"慢慢来，好戏都在烟火里",
	"Take it slow; beauty lies in mundane life",
	"心事藏于晚风，归于平静",
	"Hide thoughts in dusk, return to calm",
	"保持热爱，奔赴自己的山海",
	"Keep passion, chase your own horizon",
	"接受平庸，也保留期待",
	"Accept ordinariness, yet keep hope alive",
	"在自己的节奏里安稳度日",
	"Live steadily within your own rhythm",
	"世间喧嚣，守一方内心清净",
	"Amid chaos, guard inner serenity",
	"时光不言，却回答所有问题",
	"Silent time answers every question",
	"轻装前行，放下多余执念",
	"Travel light, let go of obsessions",
	"好好生活，慢慢相遇",
	"Live well, meet slowly",
	"风遇山止，船到岸停",
	"Wind stops at mountains, ships rest at shore",
	"心有静气，万事从容",
	"Calm heart brings ease in all things",
	"不必强求所有人理解你",
	"Don’t force everyone to understand you",
	"微小欢喜，足够支撑漫长岁月",
	"Small joys sustain the long journey",
	"夜色温柔，治愈白日疲惫",
	"Soft night heals the weariness of day",
	"守住本心，不随浪潮浮沉",
	"Stay true, do not drift with the tide",
	"所有遗憾，都是成长伏笔",
	"Regrets are foreshadows of growth",
	"静待花开，不必焦虑花期",
	"Wait for blooms, no rush for season",
	"生活本淡，用心便能生香",
	"Life is plain, yet heart makes it fragrant",
	"向内扎根，安静生长",
	"Root deep inside, grow quietly",
	"得失随缘，心无增减",
	"Gain and loss as fate, heart unchanged",
	"把烦恼交给时间消解",
	"Leave troubles for time to dissolve",
	"平凡，亦是一种圆满",
	"Ordinary life can also be complete",
	"人间朝暮，叶落惊秋",
	"Dawn and dusk, fallen leaves announce autumn",
	"心向旷野，不惧荒芜",
	"Heart toward wilderness, fear no wasteland",
	"少些期待，少些失望",
	"Less expectation, less disappointment",
	"自洽，是最好的状态",
	"Self-consistency is the finest state",
	"且喜且乐，且以永日",
	"Be glad, be joyous, through endless days",
	"温柔自持，静候晨光",
	"Keep gentle, quietly wait for dawn",
	"不必耀眼，自在就好",
	"No need to shine, just be free",
	"山河辽阔，人间值得",
	"Vast mountains and rivers, life is worthwhile",
	"消化情绪，然后继续前行",
	"Process emotions, then move forward",
	"日子清淡，平安即是幸事",
	"Simple days, peace is true blessing",
	"与生活温柔对峙",
	"Meet life with gentle resistance",
	"守住热爱，抵御荒芜",
	"Hold love tight against desolation",
	"人海浮沉，先顾好自己",
	"Adrift in crowds, care for yourself first",
	"万事尽力，其余随缘",
	"Try your best, leave rest to destiny",
	"晚风来信，寄予心事",
	"Evening wind carries letters of the heart",
	"安静沉淀，静待时机",
	"Settle down quietly, await the moment",
	"不慌不忙，自有方向",
	"No rush, you have your own direction",
	"接纳所有不完美",
	"Embrace every imperfection",
	"浅喜深爱，静度流年",
	"Light fondness, deep love, pass time gently",
	"前路漫漫，亦有灿灿",
	"Long road ahead, yet glimmers await",
	"把温柔留给自己",
	"Reserve tenderness for yourself",
	"纵有风雨，心自安然",
	"Though storms come, heart stays peaceful",
	"浮生半日，偷得清闲",
	"Snatch half a day of leisure in fleeting life",
	"不必急着给出答案",
	"No hurry to hand out answers",
	"星光微弱，亦可前行",
	"Faint starlight still guides the way",
	"放下内耗，轻身而行",
	"Stop internal friction, walk light",
	"岁月无声，温柔相伴",
	"Silent years walk with gentleness",
	"心若无尘，清风自来",
	"No dust in heart, cool wind arrives",
	"随遇而安，随喜而悦",
	"Be content wherever you are, glad for small gains",
	"好好照顾自己的情绪",
	"Tenderly take care of your emotions",
	"人间烟火，最抚人心",
	"Mortal warmth soothes the weary soul",
	"静待风起，不必强求",
	"Await the wind, force nothing",
	"忠于内心，不问喧嚣",
	"Stay true inside, ignore the noise",
	"缓慢度日，感受当下",
	"Slow down, feel the present moment",
	"所有经历，皆为馈赠",
	"Every experience is a gift",
	"静而不争，万事顺心",
	"Quiet and uncompetitive, all goes well",
	"于无声处，默默发光",
	"Shine softly in the quiet corners",
	"相逢有期，离别无碍",
	"Meet in time, part without grief",
	"风自有去向，人自有归途",
	"Wind has its way, soul has its home",
	"降低期待，拥抱平淡",
	"Lower expectations, embrace plainness",
	"守好内心那片净土",
	"Guard the pure land within your heart",
	"步履不停，自有风景",
	"Keep walking, scenery will come",
	"一念清净，万般自在",
	"One pure thought brings full freedom",
	"允许短暂的低落与停滞",
	"Allow temporary slump and pause",
	"晨光会抚平昨夜阴霾",
	"Morning light smooths last night’s gloom",
	"淡看世事，静赏繁花",
	"Watch the world lightly, admire blooms calmly",
	"自有节奏，不与人争",
	"Keep your rhythm, compete with no one",
	"心事浅藏，安然度日",
	"Hide thoughts lightly, live peacefully",
	"长路漫漫，温柔为伴",
	"Long journey, let gentleness accompany",
	"不必活成别人期待",
	"Don’t live up to others’ expectations",
	"沉淀自我，静待曙光",
	"Ground yourself, wait for first light",
	"四时有序，万物有时",
	"Seasons follow order, all things have their time",
	"释怀过往，奔赴前方",
	"Release the past, run toward tomorrow",
	"微小暖意，汇聚成光",
	"Tiny warmth gathers into bright light",
	"静看云起，淡随风落",
	"Watch clouds rise, drift away with wind",
	"自守清欢，不慕浮华",
	"Cherish simple joy, crave no vanity",
	"人生辽阔，不止眼前",
	"Life is vast, far beyond sight",
	"和解之后，方能前行",
	"Only after reconciliation can you move on",
	"晚风不语，治愈众生",
	"Silent dusk heals every soul",
	"保持松弛，不必紧绷",
	"Stay loose, no need to stay tense",
	"心有微光，不惧长夜",
	"Small inner light fears no long night",
	"流年静默，安然自守",
	"Quiet passing years, keep peace within",
	"取舍之间，即是人生",
	"Choosing and letting go makes life",
	"好好感受当下一刻",
	"Truly feel this instant right now",
	"山海自有归期，风雨自有相逢",
	"Mountains meet seas, storms bring reunion",
	"默默蓄力，静待绽放",
	"Gather strength silently, wait to bloom",
	"不恋过往，不畏将来",
	"Cling not to past, fear not what’s ahead",
	"人间本客，适度清醒",
	"We are passing guests, stay sober enough",
	"云卷云舒，自在随心",
	"Clouds roll and unfold, follow your heart",
	"日子缓缓，生活散散",
	"Slow days, unhurried living",
	"以平常心，观无常事",
	"View changing world with ordinary mind",
	"在尘埃里，保有浪漫",
	"Keep romance even amid dust",
	"不必急着证明自己",
	"No rush to prove your worth",
	"四季轮回，自有温柔",
	"Rotating seasons hold constant tenderness",
	"心藏山海，静而无边",
	"Heart hides mountains and seas, calm and boundless",
]